### PR TITLE
Added Sonoma Support

### PR DESCRIPTION
**Pull request by narcyzzo**
Tested 
Zrzut ekranu 2023-06-7 o 19 36 25

### CODE REVIEW

**Comment by Ausdauersportler** [comment]
Works on AMD RX560 (mobile) and FirePro M5100 (mobile) on Sonoma b6, too. Apple uses an AMD marketing name R9 M370X in the MacBookPro 2015. Can be confusing. It is the same chip (re-used on M6000, W5170).
Really nice work!

AdvancedMap-M5100
AdvancedMap-RX560

**Comment by narcyzzo** [comment]
https://github.com/narcyzzo/AdvancedMap/releases

**Comment by bootlegseahorse** [comment]
> https://github.com/narcyzzo/AdvancedMap/releases

Some good news to report - the 3.0.0 release is now confirmed to be working with Intel iGPUs. Hooray!

These GPUs are now confirmed supported: **Intel HD Graphics 4000**, **Intel HD Graphics 620**, **AMD Radeon R9 M390** - fully functional on both Monterey and Ventura (don't have Sonoma so haven't tested yet). These are the only GPUs I've tested - but I do believe that there are a lot more iGPUs and dGPUs supported!

**Intel HD Graphics 620** - _tested on a hackintosh MacBookPro14,1_
Maps - 2023-08-30 03:48:13

**Intel HD Graphics 4000** - _tested on a real MacBookPro9,2_
Maps - 2023-08-30 04:05:50

**AMD Radeon R9 M390** - _tested on a real iMac17,1_
Maps - 2023-08-30 04:12:28

It isn't very stable though - the Maps app crashes at times when zooming into certain cities; not sure if the crash also occurs on Apple Silicon chips or not. Or maybe it's just me. I'll test it on my father's M1 MacBook whenever I get the chance.

**Comment by notjosh** [comment]
This is awesome, thanks for this!

PR looks good to me, I'll roll it into a release later on (...I'm a bit behind on my OpenCore updates, so I'll bump it and confirm it's working for me first)

**Pull request merged**
